import type {
  User,
  YoungPerson,
  Home,
  CareGroup,
  Employee,
  Task,
  IOILog,
  Vehicle,
  CalendarEvent,
  TaskExplorerForm,
  TaskExplorerLogEntry,
} from "@/types"

// Current logged in user
export const mockUser: User = {
  id: "user-1",
  email: "sarah.johnson@nexustherapeutic.com",
  firstName: "Sarah",
  lastName: "Johnson",
  role: "manager",
  avatar: undefined,
  homeId: "home-1",
  createdAt: "2023-01-15T09:00:00Z",
}

// Dashboard statistics
export const mockStats = {
  overdue: 3,
  dueToday: 7,
  pendingApproval: 12,
  rejected: 2,
  draft: 5,
  future: 18,
  comments: 4,
  rewards: 6,
}

// Young People
export const mockYoungPeople: YoungPerson[] = [
  {
    id: "yp-1",
    firstName: "James",
    lastName: "Wilson",
    dateOfBirth: "2010-03-15",
    homeId: "home-1",
    homeName: "Maple House",
    status: "active",
    admissionDate: "2023-06-01",
    keyWorker: "Sarah Johnson",
  },
  {
    id: "yp-2",
    firstName: "Emily",
    lastName: "Brown",
    dateOfBirth: "2011-07-22",
    homeId: "home-1",
    homeName: "Maple House",
    status: "active",
    admissionDate: "2023-04-15",
    keyWorker: "Mark Thompson",
  },
  {
    id: "yp-3",
    firstName: "Oliver",
    lastName: "Davis",
    dateOfBirth: "2009-11-08",
    homeId: "home-2",
    homeName: "Oak Lodge",
    status: "active",
    admissionDate: "2022-09-20",
    keyWorker: "Emma White",
  },
  {
    id: "yp-4",
    firstName: "Sophie",
    lastName: "Taylor",
    dateOfBirth: "2012-01-30",
    homeId: "home-1",
    homeName: "Maple House",
    status: "active",
    admissionDate: "2024-01-10",
    keyWorker: "Sarah Johnson",
  },
  {
    id: "yp-5",
    firstName: "Daniel",
    lastName: "Moore",
    dateOfBirth: "2008-05-12",
    homeId: "home-2",
    homeName: "Oak Lodge",
    status: "transferred",
    admissionDate: "2021-03-05",
    keyWorker: "James Clark",
  },
]

// Homes
export const mockHomes: Home[] = [
  {
    id: "home-1",
    name: "Maple House",
    address: "123 Maple Street, Manchester, M1 2AB",
    capacity: 6,
    currentOccupancy: 4,
    manager: "Sarah Johnson",
    phone: "0161 234 5678",
    status: "active",
  },
  {
    id: "home-2",
    name: "Oak Lodge",
    address: "45 Oak Avenue, Liverpool, L2 3CD",
    capacity: 5,
    currentOccupancy: 3,
    manager: "Michael Roberts",
    phone: "0151 987 6543",
    status: "active",
  },
  {
    id: "home-3",
    name: "Willow Court",
    address: "78 Willow Lane, Leeds, LS1 4EF",
    capacity: 4,
    currentOccupancy: 2,
    manager: "Lisa Anderson",
    phone: "0113 456 7890",
    status: "active",
  },
]

// Care Groups
export const mockCareGroups: CareGroup[] = [
  {
    id: "cg-1",
    name: "North West Region",
    description: "All homes in the North West area",
    homes: ["home-1", "home-2"],
    manager: "David Williams",
  },
  {
    id: "cg-2",
    name: "Yorkshire Region",
    description: "All homes in Yorkshire",
    homes: ["home-3"],
    manager: "Jennifer Brown",
  },
]

// Employees
export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@nexustherapeutic.com",
    role: "manager",
    homeId: "home-1",
    homeName: "Maple House",
    phone: "07700 900001",
    status: "active",
    startDate: "2021-03-15",
  },
  {
    id: "emp-2",
    firstName: "Mark",
    lastName: "Thompson",
    email: "mark.thompson@nexustherapeutic.com",
    role: "staff",
    homeId: "home-1",
    homeName: "Maple House",
    phone: "07700 900002",
    status: "active",
    startDate: "2022-06-01",
  },
  {
    id: "emp-3",
    firstName: "Emma",
    lastName: "White",
    email: "emma.white@nexustherapeutic.com",
    role: "staff",
    homeId: "home-2",
    homeName: "Oak Lodge",
    phone: "07700 900003",
    status: "active",
    startDate: "2022-09-15",
  },
  {
    id: "emp-4",
    firstName: "James",
    lastName: "Clark",
    email: "james.clark@nexustherapeutic.com",
    role: "staff",
    homeId: "home-2",
    homeName: "Oak Lodge",
    phone: "07700 900004",
    status: "on-leave",
    startDate: "2021-11-01",
  },
  {
    id: "emp-5",
    firstName: "Lisa",
    lastName: "Anderson",
    email: "lisa.anderson@nexustherapeutic.com",
    role: "manager",
    homeId: "home-3",
    homeName: "Willow Court",
    phone: "07700 900005",
    status: "active",
    startDate: "2020-08-20",
  },
]

// Tasks - To Do List
export const mockToDoTasks: Task[] = [
  {
    id: "task-1",
    title: "Complete weekly health check for James Wilson",
    description: "Regular health assessment including weight, mood, and general wellbeing",
    status: "due-today",
    dueDate: new Date().toISOString(),
    assignedTo: "emp-1",
    assignedToName: "Sarah Johnson",
    youngPersonId: "yp-1",
    youngPersonName: "James Wilson",
    category: "Health & Medical",
    priority: "high",
    createdAt: "2024-01-20T09:00:00Z",
    updatedAt: "2024-01-20T09:00:00Z",
  },
  {
    id: "task-2",
    title: "Submit monthly report for Maple House",
    description: "Compile and submit the monthly operational report",
    status: "overdue",
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: "emp-1",
    assignedToName: "Sarah Johnson",
    category: "Administrative",
    priority: "high",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "task-3",
    title: "Arrange dental appointment for Emily Brown",
    description: "Schedule routine dental check-up",
    status: "due-today",
    dueDate: new Date().toISOString(),
    assignedTo: "emp-2",
    assignedToName: "Mark Thompson",
    youngPersonId: "yp-2",
    youngPersonName: "Emily Brown",
    category: "Health & Medical",
    priority: "medium",
    createdAt: "2024-01-18T09:00:00Z",
    updatedAt: "2024-01-18T09:00:00Z",
  },
  {
    id: "task-4",
    title: "Update care plan for Sophie Taylor",
    description: "Review and update the care plan following recent assessment",
    status: "future",
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: "emp-1",
    assignedToName: "Sarah Johnson",
    youngPersonId: "yp-4",
    youngPersonName: "Sophie Taylor",
    category: "Review & Assessment",
    priority: "medium",
    createdAt: "2024-01-19T09:00:00Z",
    updatedAt: "2024-01-19T09:00:00Z",
  },
  {
    id: "task-5",
    title: "Complete safeguarding training",
    description: "Annual mandatory safeguarding refresher course",
    status: "draft",
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: "emp-2",
    assignedToName: "Mark Thompson",
    category: "Training",
    priority: "low",
    createdAt: "2024-01-17T09:00:00Z",
    updatedAt: "2024-01-17T09:00:00Z",
  },
]

// Tasks - Pending Approval
export const mockApprovalTasks: Task[] = [
  {
    id: "approval-1",
    title: "IOI Log - James Wilson - Session 15/01",
    description: "Therapeutic intervention log requiring manager approval",
    status: "pending",
    dueDate: new Date().toISOString(),
    assignedTo: "emp-2",
    assignedToName: "Mark Thompson",
    youngPersonId: "yp-1",
    youngPersonName: "James Wilson",
    category: "Daily Care",
    priority: "medium",
    createdAt: "2024-01-15T14:30:00Z",
    updatedAt: "2024-01-15T14:30:00Z",
  },
  {
    id: "approval-2",
    title: "Leave request - Emma White",
    description: "Annual leave request for 5 days in February",
    status: "pending",
    dueDate: new Date().toISOString(),
    assignedTo: "emp-3",
    assignedToName: "Emma White",
    category: "Administrative",
    priority: "low",
    createdAt: "2024-01-18T11:00:00Z",
    updatedAt: "2024-01-18T11:00:00Z",
  },
  {
    id: "approval-3",
    title: "Incident report - Minor altercation",
    description: "Incident report requiring review and sign-off",
    status: "pending",
    dueDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignedTo: "emp-4",
    assignedToName: "James Clark",
    youngPersonId: "yp-3",
    youngPersonName: "Oliver Davis",
    category: "Behavioral",
    priority: "high",
    createdAt: "2024-01-19T16:45:00Z",
    updatedAt: "2024-01-19T16:45:00Z",
  },
]

// IOI Logs
export const mockLogs: IOILog[] = [
  {
    id: "log-1",
    youngPersonId: "yp-1",
    youngPersonName: "James Wilson",
    authorId: "emp-1",
    authorName: "Sarah Johnson",
    sessionDate: "2024-01-20T10:00:00Z",
    location: "Common Room",
    status: "approved",
    input: {
      situation: "James appeared withdrawn during breakfast and refused to engage with peers. Staff observed signs of anxiety including fidgeting and avoiding eye contact.",
      clientState: "Anxious, withdrawn, low mood",
      goals: "To help James express his feelings and reduce anxiety levels",
    },
    output: {
      intervention: "Initiated a one-to-one conversation using active listening techniques. Provided a calm, private space in the common room. Used grounding exercises (5-4-3-2-1 technique) to help manage anxiety.",
      techniques: ["Active Listening", "Grounding Exercises", "Trauma-Informed Care"],
      duration: 45,
    },
    impact: {
      immediateImpact: "James gradually opened up about worries regarding upcoming family contact. Anxiety visibly reduced - stopped fidgeting and made eye contact.",
      clientResponse: "James expressed gratitude for the conversation and asked if we could do regular check-ins.",
      followUpNeeded: true,
      notes: "Schedule follow-up before family contact visit next week. Consider involving therapist if anxiety persists.",
    },
    createdAt: "2024-01-20T11:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    approvedBy: "Michael Roberts",
    approvedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "log-2",
    youngPersonId: "yp-2",
    youngPersonName: "Emily Brown",
    authorId: "emp-2",
    authorName: "Mark Thompson",
    sessionDate: "2024-01-19T14:00:00Z",
    location: "Garden",
    status: "pending",
    input: {
      situation: "Emily had a disagreement with another young person during lunch. She left the table upset and went to her room.",
      clientState: "Upset, angry, frustrated",
      goals: "Help Emily process her emotions and develop conflict resolution skills",
    },
    output: {
      intervention: "After allowing Emily time to calm down, approached her and offered to talk in the garden. Used reflective practice to help her understand her emotions and the other person's perspective.",
      techniques: ["Reflective Practice", "Emotion Regulation", "Social Skills Training"],
      duration: 30,
    },
    impact: {
      immediateImpact: "Emily was able to identify that she felt unheard and that her reaction was disproportionate. She agreed to apologise.",
      clientResponse: "Positive - Emily thanked staff for not taking sides and helping her see the situation clearly.",
      followUpNeeded: false,
      notes: "Monitor interactions at mealtimes over the next few days.",
    },
    createdAt: "2024-01-19T15:00:00Z",
    updatedAt: "2024-01-19T15:00:00Z",
  },
  {
    id: "log-3",
    youngPersonId: "yp-4",
    youngPersonName: "Sophie Taylor",
    authorId: "emp-1",
    authorName: "Sarah Johnson",
    sessionDate: "2024-01-18T16:00:00Z",
    location: "Bedroom",
    status: "draft",
    input: {
      situation: "Sophie requested help with homework but became frustrated when she couldn't understand the maths problems.",
      clientState: "Frustrated, low confidence",
      goals: "Support Sophie with homework while building confidence",
    },
    output: {
      intervention: "Broke down the problems into smaller steps. Used positive reinforcement when she got answers correct. Took breaks when frustration built up.",
      techniques: ["Positive Reinforcement", "Solution-Focused Approach"],
      duration: 60,
    },
    impact: {
      immediateImpact: "Sophie completed her homework with support. Her confidence improved as she solved problems independently by the end.",
      clientResponse: "Sophie said she felt proud of herself and asked if we could do homework help sessions regularly.",
      followUpNeeded: true,
      notes: "Arrange regular homework support. Consider liaising with school about additional learning support.",
    },
    createdAt: "2024-01-18T17:30:00Z",
    updatedAt: "2024-01-18T17:30:00Z",
  },
]

// Vehicles
export const mockVehicles: Vehicle[] = [
  {
    id: "veh-1",
    registration: "AB12 CDE",
    make: "Ford",
    model: "Transit Custom",
    homeId: "home-1",
    homeName: "Maple House",
    status: "available",
    mileage: 45230,
    nextServiceDate: "2024-03-15",
  },
  {
    id: "veh-2",
    registration: "XY34 FGH",
    make: "Volkswagen",
    model: "Caddy",
    homeId: "home-2",
    homeName: "Oak Lodge",
    status: "in-use",
    mileage: 32100,
    nextServiceDate: "2024-02-28",
  },
  {
    id: "veh-3",
    registration: "LM56 NOP",
    make: "Vauxhall",
    model: "Vivaro",
    homeId: "home-3",
    homeName: "Willow Court",
    status: "maintenance",
    mileage: 67800,
    nextServiceDate: "2024-01-25",
  },
]

// Calendar Events
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: "event-1",
    title: "Team Meeting",
    date: new Date().toISOString().split("T")[0],
    startTime: "10:00",
    endTime: "11:00",
    type: "meeting",
    description: "Weekly team catch-up",
    participants: ["Sarah Johnson", "Mark Thompson"],
  },
  {
    id: "event-2",
    title: "James Wilson - School Review",
    date: new Date().toISOString().split("T")[0],
    startTime: "14:00",
    endTime: "15:00",
    type: "appointment",
    description: "Termly review meeting at school",
  },
  {
    id: "event-3",
    title: "Safeguarding Training",
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "09:00",
    endTime: "12:00",
    type: "training",
    description: "Annual mandatory training session",
    participants: ["All Staff"],
  },
  {
    id: "event-4",
    title: "Emily Brown - Family Contact",
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    startTime: "15:00",
    endTime: "16:30",
    type: "appointment",
    description: "Supervised family contact visit",
  },
]

// Task Explorer — Forms
export const mockTaskExplorerForms: TaskExplorerForm[] = [
  {
    id: "form-1",
    name: "Daily Care Record",
    category: "Daily Care",
    fields: [
      { id: "f1-1", label: "Young Person", type: "select", required: true },
      { id: "f1-2", label: "Date", type: "date", required: true },
      { id: "f1-3", label: "Mood Assessment", type: "select", required: true },
      { id: "f1-4", label: "Activities", type: "text", required: false },
      { id: "f1-5", label: "Notes", type: "text", required: false },
    ],
    lastUpdated: "2026-02-08T10:00:00Z",
  },
  {
    id: "form-2",
    name: "Health Check Form",
    category: "Health & Medical",
    fields: [
      { id: "f2-1", label: "Young Person", type: "select", required: true },
      { id: "f2-2", label: "Check Date", type: "date", required: true },
      { id: "f2-3", label: "Weight (kg)", type: "number", required: true },
      { id: "f2-4", label: "Temperature", type: "number", required: false },
      { id: "f2-5", label: "General Wellbeing", type: "select", required: true },
      { id: "f2-6", label: "Follow-up Required", type: "checkbox", required: false },
    ],
    lastUpdated: "2026-02-07T14:30:00Z",
  },
  {
    id: "form-3",
    name: "Incident Report Form",
    category: "Behavioral",
    fields: [
      { id: "f3-1", label: "Incident Date", type: "date", required: true },
      { id: "f3-2", label: "Incident Type", type: "select", required: true },
      { id: "f3-3", label: "Young People Involved", type: "select", required: true },
      { id: "f3-4", label: "Description", type: "text", required: true },
      { id: "f3-5", label: "Action Taken", type: "text", required: true },
    ],
    lastUpdated: "2026-02-06T09:15:00Z",
  },
  {
    id: "form-4",
    name: "Care Plan Review",
    category: "Review & Assessment",
    fields: [
      { id: "f4-1", label: "Young Person", type: "select", required: true },
      { id: "f4-2", label: "Review Date", type: "date", required: true },
      { id: "f4-3", label: "Goals Progress", type: "text", required: true },
      { id: "f4-4", label: "Updated Goals", type: "text", required: true },
      { id: "f4-5", label: "Next Review Date", type: "date", required: true },
    ],
    lastUpdated: "2026-02-05T11:00:00Z",
  },
  {
    id: "form-5",
    name: "Risk Assessment",
    category: "Review & Assessment",
    fields: [
      { id: "f5-1", label: "Young Person", type: "select", required: true },
      { id: "f5-2", label: "Assessment Date", type: "date", required: true },
      { id: "f5-3", label: "Risk Level", type: "select", required: true },
      { id: "f5-4", label: "Risk Factors", type: "text", required: true },
      { id: "f5-5", label: "Mitigation Plan", type: "text", required: true },
    ],
    lastUpdated: "2026-02-04T16:45:00Z",
  },
  {
    id: "form-6",
    name: "Medication Administration",
    category: "Health & Medical",
    fields: [
      { id: "f6-1", label: "Young Person", type: "select", required: true },
      { id: "f6-2", label: "Medication Name", type: "text", required: true },
      { id: "f6-3", label: "Dosage", type: "text", required: true },
      { id: "f6-4", label: "Time Administered", type: "date", required: true },
      { id: "f6-5", label: "Administered By", type: "select", required: true },
    ],
    lastUpdated: "2026-02-09T08:00:00Z",
  },
  {
    id: "form-7",
    name: "Key Worker Session",
    category: "Daily Care",
    fields: [
      { id: "f7-1", label: "Young Person", type: "select", required: true },
      { id: "f7-2", label: "Session Date", type: "date", required: true },
      { id: "f7-3", label: "Topics Discussed", type: "text", required: true },
      { id: "f7-4", label: "Goals Set", type: "text", required: false },
      { id: "f7-5", label: "Next Session", type: "date", required: false },
    ],
    lastUpdated: "2026-02-03T13:20:00Z",
  },
]

// Task Explorer — Log Entries (matches real table columns)
export const mockTaskExplorerLogs: TaskExplorerLogEntry[] = [
  {
    id: "log-1",
    taskId: 796,
    title: "Absence/Missing Form - PE 09/02/2026 (4)",
    formGroup: "Absence Form",
    relatesTo: "Peniel Essouma",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 10:28:00 PM",
    status: "draft",
    originallyRecordedAt: "09/02/2026 11:30:23 PM",
    originallyRecordedBy: "Kwadwo",
  },
  {
    id: "log-2",
    taskId: 725,
    title: "Medication Prescribed",
    formGroup: "Medication Dispensed",
    relatesTo: "CAITLIN SMITH",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:47:00 PM",
    status: "sent-for-approval",
    originallyRecordedAt: "09/02/2026 8:49:55 PM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-3",
    taskId: 722,
    title: "Daily Summary - 09/02/2026",
    formGroup: "Daily Summary",
    relatesTo: "CAITLIN SMITH",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:36:00 PM",
    status: "draft",
    originallyRecordedAt: "09/02/2026 8:45:19 PM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-4",
    taskId: 743,
    title: "PM sharps check",
    formGroup: "Daily AM sharps check",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:32:00 PM",
    status: "submitted",
    originallyRecordedAt: "09/02/2026 8:33:44 PM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-5",
    taskId: 721,
    title: "Daily Summary - 09/02/2026 (8)",
    formGroup: "Daily Summary",
    relatesTo: "Peniel Essouma",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 5:54:00 PM",
    status: "draft",
    originallyRecordedAt: "09/02/2026 11:48:16 PM",
    originallyRecordedBy: "Masud",
  },
  {
    id: "log-6",
    taskId: 738,
    title: "Professional Contact 09/02/2026",
    formGroup: "Professional Contact",
    relatesTo: "CAITLIN SMITH",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 5:48:00 PM",
    status: "sent-for-approval",
    originallyRecordedAt: "09/02/2026 6:53:43 PM",
    originallyRecordedBy: "Masud",
  },
  {
    id: "log-7",
    taskId: 734,
    title: "Cleaning Schedule",
    formGroup: "Daily Cleaning Schedule",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 4:37:00 PM",
    status: "approved",
    originallyRecordedAt: "09/02/2026 5:38:11 PM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-8",
    taskId: 737,
    title: "Ligature Check",
    formGroup: "Daily Ligature Check",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:45:00 AM",
    status: "approved",
    originallyRecordedAt: "09/02/2026 8:45:58 AM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-9",
    taskId: 733,
    title: "AM sharps check",
    formGroup: "Daily AM sharps check",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:44:00 AM",
    status: "submitted",
    originallyRecordedAt: "09/02/2026 8:45:22 AM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-10",
    taskId: 728,
    title: "Fridge/Freezer Temps Checks",
    formGroup: "Fridge/Freezer Temps",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:43:00 AM",
    status: "submitted",
    originallyRecordedAt: "09/02/2026 8:44:32 AM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-11",
    taskId: 716,
    title: "Waking Night Summary - 09/02/2026 (8)",
    formGroup: "Waking Night Summary",
    relatesTo: "CAITLIN SMITH",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 12:42:00 AM",
    status: "rejected",
    originallyRecordedAt: "09/02/2026 8:30:34 AM",
    originallyRecordedBy: "Miracle",
  },
  {
    id: "log-12",
    taskId: 717,
    title: "Daily Cleaning Schedule - 09/02/2026 (2)",
    formGroup: "Daily Cleaning Schedule",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 12:40:00 AM",
    status: "approved",
    originallyRecordedAt: "09/02/2026 1:42:08 AM",
    originallyRecordedBy: "Miracle",
  },
  {
    id: "log-13",
    taskId: 723,
    title: "Daily Handover - 09/02/2026 (4)",
    formGroup: "Daily Handover",
    relatesTo: "Peniel Essouma",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 12:00:00 AM",
    status: "sent-for-approval",
    originallyRecordedAt: "09/02/2026 11:26:33 PM",
    originallyRecordedBy: "Masud",
  },
  {
    id: "log-14",
    taskId: 740,
    title: "Petty Cash 09/02/2026",
    formGroup: "Petty Cash",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 3:15:00 PM",
    status: "draft",
    originallyRecordedAt: "09/02/2026 4:20:00 PM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-15",
    taskId: 729,
    title: "Daily Window Restrictor checks",
    formGroup: "Daily Window Restrictor checks",
    relatesTo: "The Homeland",
    relatesToIcon: "home",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 7:40:00 AM",
    status: "submitted",
    originallyRecordedAt: "09/02/2026 8:42:15 AM",
    originallyRecordedBy: "Penn",
  },
  {
    id: "log-16",
    taskId: 724,
    title: "Daily Handover - 09/02/2026 (7)",
    formGroup: "Daily Handover",
    relatesTo: "CAITLIN SMITH",
    relatesToIcon: "person",
    homeOrSchool: "The Homeland",
    taskDate: "09/02/2026 12:00:00 AM",
    status: "deleted",
    originallyRecordedAt: "09/02/2026 11:30:00 PM",
    originallyRecordedBy: "Masud",
  },
]

// Task Explorer — Form Submission Chart Data
export interface FormSubmissionData {
  name: string
  count: number
  color: string
}

export const mockFormSubmissions: FormSubmissionData[] = [
  { name: "Petty Cash", count: 1, color: "#00BFFF" },
  { name: "Daily Handover", count: 2, color: "#9E9E9E" },
  { name: "Daily Summary", count: 2, color: "#FF3B30" },
  { name: "Absence Form", count: 1, color: "#FF9500" },
  { name: "Professional Contact", count: 1, color: "#4CD964" },
  { name: "Medication Dispensed", count: 1, color: "#34C759" },
  { name: "Fridge/Freezer Temps", count: 1, color: "#FFCC00" },
  { name: "Daily Window Restrictor checks", count: 1, color: "#FF6B6B" },
  { name: "Daily AM sharps check", count: 2, color: "#FF2D55" },
  { name: "Daily Cleaning Schedule", count: 2, color: "#FF9500" },
  { name: "Waking Night Summary", count: 1, color: "#AF52DE" },
  { name: "Daily Ligature Check", count: 1, color: "#5856D6" },
]

// Helper function to get young person by ID
export function getYoungPersonById(id: string): YoungPerson | undefined {
  return mockYoungPeople.find((yp) => yp.id === id)
}

// Helper function to get employee by ID
export function getEmployeeById(id: string): Employee | undefined {
  return mockEmployees.find((emp) => emp.id === id)
}

// Helper function to get home by ID
export function getHomeById(id: string): Home | undefined {
  return mockHomes.find((home) => home.id === id)
}

// Helper function to get log by ID
export function getLogById(id: string): IOILog | undefined {
  return mockLogs.find((log) => log.id === id)
}
